<?php
//Note: All entries must be compatible with javascript syntax. HTML tags will not be parsed.

//Preferences
$langmk['had_boardname'] = "Valore utilizzato da MKPortal per identificare il tipo di forum da te in uso. Questo valore pu&ograve; essere cambiato solamente modificando il file mkportal/conf_mk.php.";
$langmk['had_siteurl'] = "L\' indirizzo completo del tuo sito con MKPortal. Questo valore pu&ograve; essere cambiato solamente modificando il file mkportal/conf_mk.php.";
$langmk['had_adminpath'] = "&Egrave; consigliato per motivi di sicurezza cambiare il nome della cartella \"admin\". Per cambiare il nome della cartella admin: (1) Rinomina la cartella \"admin\" con qualcosa che &egrave; difficile da indovinare come una buona password. Esempio: \"ride2live\". (2) Modifica il file mkportal/conf_mk.php impostando il nuovo nome della cartella admin. Esempio \$ADMIN_PATH = \"ride2live\"; Questo valore pu&ograve; essere cambiato solamente modificando il file mkportal/conf_mk.php. ";
$langmk['had_fpath'] = "Il nome della cartella del forum. Da non intendersi come il percorso al forum, ma solo il nome della cartella. Questo valore pu&ograve; essere cambiato solamente modificando il file mkportal/conf_mk.php.";
$langmk['had_sitename'] = "Il nome del tuo sito web. Questo sar&agrave; utilizzato nel titolo del browser e in altri punti in MKPortal. I Titoli sono molto importanti per il SEO. Utilizzali saggiamente.";
$langmk['had_putoff'] = "Imposta su \"Si\" per mettere il tuo sito in \"modalit&agrave; manutenzione\". Sia il portale che il forum saranno offline. Gli admin che saranno loggati continueranno a vedere il sito. Se per sbaglio ti sei sloggato mentre il tuo sito era in modalit&agrave; offline entra semplicemente nel tuo server ftp e modifica il file conf_mk.php. Imposta \$MK_OFFLINE = \"0\"; Zero \"0\" significa che il portale NON &Egrave; offline. Uno \"1\" significa che &Egrave; offline.";
$langmk['had_lang'] = "La lingua di default per il tuo sito. La lingua pu&ograve; essere cambiata dagli utenti se tu lo imposti nei permessi del tuo forum e se hai installate le traduzioni corrispondenti per il forum e il portale. Per esempio se vuoi che un utente pu&ograve; scegliere la lingua Spagnola devi avere la lingua Spagnola per MKPortal installata e la lingua Spagnola per il forum installata.";
$langmk['had_editor'] = "L\' editor presente in MKPortal &egrave; TinyMCE WYSIWYG editor. L\' editor BBcode &egrave; di propriet&agrave; di MKPortal. Nota che i contenuti inseriti tramite gli editor sono filtrati per motivi di sicurezza. Il contenuto inserito tramite CPA Portale non &egrave; filtrato e permette agli admin di usare tutti i codici html e javascript. Poich&egrave; TinyMCE filtra alcuni codici &egrave; consigliato agli Admin di usare l\' editor BBcode per aggiungere il contenuto da CPA Portale.";
$langmk['had_disablezip'] = "Utilizzando la compressione gzip si risparmier&agrave; banda e i tempi di caricamento pagina diminuiranno. Comunque, se il tuo server non supporta questa funzione puoi disabilitarla con questo settaggio.";
$langmk['had_sytime'] = "Utilizza questa opzione per sincronizzare l\' orario di MKPortal con l\' orario del tuo forum";
$langmk['had_metadesc'] = "Utilizzate nel tag meta \"description\". Meta descriptions sono molto importanti per il SEO. Descrivi il tuo sito utilizzando un paio di frasi con parole chiavi. Ma non troppo lunghe.";
$langmk['had_metakey'] = "Utilizzate nel tag meta \"keywords\". Meta keywords non sono in genere molto importanti per il SEO. Non utilizzarne troppe.";
$langmk['had_skin'] = "Imposta il template di MKPortal. Utilizza il template \"Forum\" di MKPortal per importare automaticamente il css del forum nel portale. I nuovi template di MKPortal possono essere installati semplicemente uploadando la cartella del nuovo template in mkportal/templates. Assicurati che il template sia compatibile con la tua versione di MKPortal.";
$langmk['had_powidth'] = "Imposta la larghezza in pixel per impostare il tuo template ad una larghezza fissa. Imposta il template con una percentuale per rendere il template ridimensionato a seconda del browser di chi lo visita. Questa funzione potrebbe non essere supportata da tutti i template di terze parti. Ricorda che una larghezza molto piccola potrebbe creare problemi di visualizzazione con alcuni moduli come TopSite, Classifica Blog, e la visualizzazione del forum.";
$langmk['had_disablenav'] = "Imposta su si \"Si\" per disabilitare la barra di navigazione.";
$langmk['had_noicons'] = "Abilita o Disabilita le icone nei link di navigazione. Questo settaggio ha effetto sui link della barra di navigazione e in tutti i blocchi di MKPortal.";
$langmk['had_cowidth'] = "Imposta la larghezza in pixel per le colonne laterali di MKPortal. Inserisci solo un valore numerico. Non aggiungere \"px\" in quanto &egrave; compreso.";
$langmk['had_load_leftc'] = "Disabilitare o \"Non Caricare\" una colonna significa che la colonna non sar&agrave; inizializzata da MKPortal. Questo settaggio &egrave; globale solo nel portale. Ci&ograve; &egrave; differente rispetto alla \"chiusura forzata\" di una colonna in quanto significa che la colonna &egrave; caricata dallo script php ma &egrave; nascosta dal client-side utilizzando uno javascript.";
$langmk['had_load_rightc'] = "Disabilitare o \"Non Caricare\" una colonna significa che la colonna non sar&agrave; inizializzata da MKPortal. Questo settaggio &egrave; globale solo nel portale. Ci&ograve; &egrave; differente rispetto alla \"chiusura forzata\" di una colonna in quanto significa che la colonna &egrave; caricata dallo script php ma &egrave; nascosta dal client-side utilizzando uno javascript.";
$langmk['had_foot_logo'] = "Sebbene la licenza di MKPortal non permette di modificare il copyright, &egrave; perfettamente accettabile se preferisci nascondere il logo di MKPortal";
$langmk['had_foot_version'] = "Alcuni Admin preferiscono nascondere il numero della versione perch&egrave; ci&ograve; pu&ograve; rendere leggermente pi&ugrave; difficile per i  \"crackers\" individuare programmi vulnerabili online. Ci&ograve; non &egrave; un problema se mantieni i tuoi script aggiornati. Altri admin preferiscono mostrare il numero della versione cosi che i loro utenti sanno che il sito usa l\' ultima versione.";
$langmk['had_foot_debug'] = "Mostra nel footer il tempo di generazione della pagina e il numero delle query in totale. Utilizzati principalmente nelle operazioni di debugging di blocchi, moduli o hack personalizzati o quando si hanno altri problemi con il sito.";
$langmk['had_forumin'] = "Imposta su \"Si\" per mostrare il tuo forum dentro MKPortal. ATTENZIONE! &Egrave; necessario anche modificare uno o pi&ugrave; file del forum per far si che questa opzione abbia effetto. Leggi le istruzioni nel file readme.htm incluso nel pacchetto di MKPortal.";
$langmk['had_rightcolumn'] = "\"Forzare la chiusura\" di una colonna significa che la colonna &egrave; caricata dallo script ma &egrave; nascosta dal client-side utilizzando uno javascript. Questo permette agli utenti di aprire o chiudere la colonna a seconda delle loro preferenze. Ci&ograve; &egrave; differente dal \"non caricare\" una colonna che significa che la colonna non &egrave; inizializzata da MKPortal.";
$langmk['had_leftcolumn'] = "\"Forzare la chiusura\" di una colonna significa che la colonna &egrave; caricata dallo script ma &egrave; nascosta dal client-side utilizzando uno javascript. Questo permette agli utenti di aprire o chiudere la colonna a seconda delle loro preferenze. Ci&ograve; &egrave; differente dal \"non caricare\" una colonna che significa che la colonna non &egrave; inizializzata da MKPortal.";
$langmk['had_uleftcolumn'] = "Disabilitare o \"Non Caricare\" una colonna significa che la colonna non sar&agrave; inizializzata da MKPortal. Questo settaggio &egrave; globale solo nel forum. Ci&ograve; &egrave; differente rispetto alla \"chiusura forzata\" di una colonna in quanto significa che la colonna &egrave; caricata dallo script php ma &egrave; nascosta dal client-side utilizzando uno javascript.";
$langmk['had_urightcolumn'] = "Disabilitare o \"Non Caricare\" una colonna significa che la colonna non sar&agrave; inizializzata da MKPortal. Questo settaggio &egrave; globale solo nel forum. Ci&ograve; &egrave; differente rispetto alla \"chiusura forzata\" di una colonna in quanto significa che la colonna &egrave; caricata dallo script php ma &egrave; nascosta dal client-side utilizzando uno javascript.";



$langmk['had_cp_tpl'] = "Questo settaggio permette di usare il template \"default\" di MKPortal nel CPA Portale. Questo settaggio imposta inoltre la larghezza nel CPA Portale al \"100%\" che &egrave; ottima per il CPA. Se stai utilizzando un template di MKPortal stretto questa opzione &egrave; consigliata per la corretta visualizzazione dei settaggi.";



//RSS
$langmk['had_rss_parser'] = "Seleziona il lettore RSS da utilizzare per mostrare i feed RSS. Ogni lettore RSS ha i suoi vantaggi e le sue limitazioni. Ricorda di attivare e posizionare il blocco corrispondente in CPA Portale &gt; Blocchi &gt; Posizione. Il blocco RSS di MKPortal si chiama \"rss.php\" invece il blocco RSS SimplePie si chiama \"rss_simplepie.php\".";
$langmk['had_rss_desc'] = "Imposta il numero massimo di caratteri nei dettagli RSS. Impostando questo valore i tag html saranno rimossi. Per evitare la rimozione dei tag html lascia questo campo vuoto oppure inserisci \"0\" ";
$langmk['had_max_items'] = "Il numero di feed da visualizzare per ogni canale.";
$langmk['had_desc'] = "Seleziona questo per visualizzare la descrizione dei feed.";
$langmk['had_cache_time'] = "Aggiornamento della cache in secondi. Esempi: 60 = 1 minuto; 300 = 5 minuti; 600 = 10 minuti; 3600 = 1 ora";
$langmk['had_marquee'] = "Scrolla le news RSS verso l\' alto. Nota: questa funzione usa il tag html &lt;marquee&gt; che non &egrave; xhtml valido. Comunque funzioner&agrave; con la maggior parte dei browser moderni.";
$langmk['had_marquee_height'] = "Imposta l\' altezza del blocco RSS quando si usa la funzione di scroll. Questo valore non deve essere vuoto oppure \"0\" se utilizzi la funzione di scroll. Questo settaggio non ha effetto quando non si utilizza lo scroll.";
$langmk['had_rss_media'] = "RSS enclosures includono media incorporati come Media RSS, iTunes RSS ecc. Questa funzione &egrave; disponibile solo con SimplePie.";
$langmk['had_rss_css'] = "Formatta il blocco RSS utilizzando uno stylesheet separato. Lo stylesheet si trova in mkportal/modules/rss/files/simplepie.css.";
$langmk['had_sp_compat'] = "Fai click su questo link per avviare il test di compatibilit&agrave; del server con SimplePie. Questo test ti mostrer&agrave; se il tuo server ha i requisiti minimi per usare il lettore RSS SimplePie. Se il tuo server non raggiunge i requisiti minimi questo test ti dir&agrave; esattamente cosa non va. Il link si aprir&agrave; in una nuova finestra.";
$langmk['had_source_pos'] = "Mostra l\'ordine per i canali RSS.";
$langmk['had_source_name'] = "Dai un nome al feed.";
$langmk['had_source_url'] = "Inserisci l\' indirizzo completo di un feed valido.";
$langmk['had_test'] = "Dopo aver salvato i tuoi settaggi puoi usare il link \"Test\" per vedere se il feed &egrave; valido. Il tuo lettore RSS &egrave; determinato dai settaggi del browser. I link si apriranno in una nuova finestra.";
$langmk['had_save_clean'] = "Fai click su \"Salva\" per aggiornare la tua configurazione RSS o dei feed. Ricorda di attivare sopra i tuoi feed altrimenti non verranno mostrati nel blocco RSS. Il bottone \"Pulisci Cache\" aggiorner&agrave; i feed salvati temporaneamente nella cartella mkportal/cache. Se il tuo blocco RSS non mostra i tuoi ultimi settaggi utilizza questa funzione per aggiornare la cache RSS.";
$langmk['had_referer'] = "Il controllo HTTP_REFERER &egrave; progettato solo per aiutare gli admin a riconoscere un certo tipo di attacchi \"social engineering\ causati dal click su link malevoli. Se stai usando un firewall assicurati che permetta il passaggio del referer info al tuo dominio. Se ti appare il messaggio d\' errore \"Azione Non Permessa\" quando provi ad accedere al CPA Portale hai bisogno di disabilitare questo settaggio editando impostando nel conf_mk.php \$MK_REFERER = \"1\"; ";
$langmk['had_postwhitelist'] = "Lista di hostname consentiti ad inviare \$_POST al tuo sito. Per esempio, se hai processi di pagamenti sul tuo sito il processore potrebbe restituire alcuni dati al tuo sito per mostrare ad esempio una pagina di ringraziamento, ecc.Il controllo HTTP_REFERER per \"POST\" &egrave; utilizzato quando si inviano form web ed &egrave; progettato per fermare bot e altri tipi di attacchi da server remoti. Se gli utenti ricevono il messaggio di errore \"Questo dominio non &egrave: nella white-list per richiedere POST.\" quando inviano form loro devono permettere al firewall o al browser di passare le informazioni di referer al tuo dominio. In alternativa puoi disabilitare questo controllo per tutti gli utenti selezionando \"disabilita\" nell\' input box \"POST\" Whitelist.";
$langmk['had_rss_merge'] = "Unisce elementi provenienti da pi&ugrave; fonti e li ordina per data.";

//Blocks
$langmk['had_sbllist'] = "I blocchi di \"Sistema\" sono i blocchi che sono stati uploadati come file PHP nella cartella mkportal/blocks. Questi includono i blocchi di default di MKPortal come pure i blocchi uplodati dall\' admin via ftp.";
$langmk['had_bllist'] = "I blocchi \"Personali\" sono i blocchi creati tramite CPA Portale. Il contenuto dei blocchi HTML e dei blocchi con i link delle pagine interne sono memorizzati nella tabella mkp_blocks nel database. Il contenuto dei blocchi PHP &egrave; memorizzato come file di cache nella cartella mkportal/cache. I file dei blocchi PHP si chiamano \"pblock_x.php\" dove la \"x\" &egrave; l\' ID del blocco.";

//Pages
$langmk['had_mcont'] = "Il contenuto delle Pagine interne HTML &egrave; memorizzato nella tabella mkp_pages del database. Il contenuto delle Pagine interne PHP &egrave; memorizzato  come file di cache nella cartella mkportal/cache. I file delle pagine interne PHP si chiamano \"ppage_x.php\" dove la \"x\" &egrave; l\'id della pagina";


?>